find_package(ament_cmake_gtest REQUIRED)
find_package(ament_cmake_ros REQUIRED)
find_package(launch_testing_ament_cmake REQUIRED)

function(add_ros_isolated_launch_test path)
  set(RUNNER "${ament_cmake_ros_DIR}/run_test_isolated.py")
  add_launch_test("${path}" RUNNER "${RUNNER}" ${ARGN})
endfunction()

add_subdirectory(outside_safety_area_should_disarm)
add_subdirectory(topic_check_failure_should_disarm)
add_subdirectory(takeoff_should_fail_while_moving)
add_subdirectory(takeoff_should_succeed)
add_subdirectory(trigger_takeoff_off_should_finish)
add_subdirectory(errorgraph_clears_after_startup)
add_subdirectory(started_armed_should_take_off)
add_subdirectory(started_armed_should_not_disarm)
add_subdirectory(already_flying_should_finish)
add_subdirectory(manual_flight_should_pause)
add_subdirectory(midair_activation_should_finish)
add_subdirectory(short_manual_should_resume)
add_subdirectory(disarm_should_start_over)
add_subdirectory(takeoff_failure_should_finish)
