# delayed takeoff
pre_takeoff_sleep: 0.0 # [s]

# A timeout between the takeoff being triggered and the UAV actually taking off
# while the timeout is counting down, the takeoff can be aborted by switching off
# the offboard mode.
# default = 5 sec
safety_timeout: 5.0 # [s]

# true: will cause the UAV to take off
# false: will perform all checks and enable control output, but the service
#     uav_manager/takeoff needs to be called manually.
handle_takeoff: true

preflight_check:

  velocity_check:

    enabled: true

    max_speed: 0.3 # [m/s]

  # the node will wait for the following topics and won't allow
  # takeoff until some data apear on them
  topic_check:

    enabled: true
    timeout: 5.0 # [s], allowed timeout for the last accepted message

    # if "/" is provided at the beginning of topic_name, the topic name is considered as written,
    # if there is no "/" at the beginning, UAV_NAME is automatically added in front of the topic name (e.g., /uav1/topic_name)
    topics: [
      "estimation_manager/uav_state",
      "control_manager/diagnostics",
    ]
